from datetime import datetime
from typing import Dict, List

WARD_SEED: List[Dict] = [
    {
        "id": 1,
        "name": "Nayapalli",
        "epi_score": 0.81,
        "solar_ghi": 5.8,
        "outage_hours": 7.2,
        "burden_pct": 14.3,
        "income_decile": 2,
        "lat": 20.2961,
        "lng": 85.8245,
    },
    {
        "id": 2,
        "name": "Saheed Nagar",
        "epi_score": 0.74,
        "solar_ghi": 5.5,
        "outage_hours": 6.1,
        "burden_pct": 12.8,
        "income_decile": 3,
        "lat": 20.2880,
        "lng": 85.8420,
    },
    {
        "id": 3,
        "name": "Bomikhal",
        "epi_score": 0.68,
        "solar_ghi": 5.2,
        "outage_hours": 5.5,
        "burden_pct": 11.2,
        "income_decile": 4,
        "lat": 20.2750,
        "lng": 85.8380,
    },
    {
        "id": 4,
        "name": "Kharvel Nagar",
        "epi_score": 0.44,
        "solar_ghi": 4.8,
        "outage_hours": 3.8,
        "burden_pct": 8.4,
        "income_decile": 5,
        "lat": 20.2700,
        "lng": 85.8300,
    },
    {
        "id": 5,
        "name": "Master Canteen",
        "epi_score": 0.31,
        "solar_ghi": 4.5,
        "outage_hours": 2.1,
        "burden_pct": 6.2,
        "income_decile": 6,
        "lat": 20.2650,
        "lng": 85.8350,
    },
    {
        "id": 6,
        "name": "BJB Nagar",
        "epi_score": 0.22,
        "solar_ghi": 4.3,
        "outage_hours": 1.4,
        "burden_pct": 4.8,
        "income_decile": 7,
        "lat": 20.2600,
        "lng": 85.8400,
    },
    {
        "id": 7,
        "name": "Jaydev Vihar",
        "epi_score": 0.15,
        "solar_ghi": 4.1,
        "outage_hours": 0.9,
        "burden_pct": 3.2,
        "income_decile": 8,
        "lat": 20.3050,
        "lng": 85.8180,
    },
    {
        "id": 8,
        "name": "Patia",
        "epi_score": 0.77,
        "solar_ghi": 5.9,
        "outage_hours": 6.8,
        "burden_pct": 13.9,
        "income_decile": 2,
        "lat": 20.3200,
        "lng": 85.8150,
    },
    {
        "id": 9,
        "name": "Chandrasekharpur",
        "epi_score": 0.52,
        "solar_ghi": 5.0,
        "outage_hours": 4.2,
        "burden_pct": 9.1,
        "income_decile": 5,
        "lat": 20.3100,
        "lng": 85.8100,
    },
    {
        "id": 10,
        "name": "Old Town",
        "epi_score": 0.71,
        "solar_ghi": 5.6,
        "outage_hours": 5.9,
        "burden_pct": 12.1,
        "income_decile": 3,
        "lat": 20.2400,
        "lng": 85.8350,
    },
]

INTERVENTION_SEED: List[Dict] = [
    {
        "id": 1,
        "rank": 1,
        "name": "Rooftop Solar + BESS Cluster",
        "wards_covered": "Aiginia/Nayapalli",
        "households": 1240,
        "cost_lakh": 48.0,
        "hh_per_lakh": 25.8,
        "type": "quick",
        "description": "Clustered rooftop solar with shared battery storage to reduce outages.",
    },
    {
        "id": 2,
        "rank": 2,
        "name": "Community Solar Microgrid",
        "wards_covered": "Patia/Old Town",
        "households": 980,
        "cost_lakh": 42.0,
        "hh_per_lakh": 23.3,
        "type": "infra",
        "description": "Community-scale microgrid for high-burden wards.",
    },
    {
        "id": 3,
        "rank": 3,
        "name": "Smart Meter + Demand Response",
        "wards_covered": "Saheed Nagar",
        "households": 760,
        "cost_lakh": 35.0,
        "hh_per_lakh": 21.7,
        "type": "quick",
        "description": "Smart meters and incentives to flatten peaks and reduce outages.",
    },
    {
        "id": 4,
        "rank": 4,
        "name": "Grid Feeder Upgrade",
        "wards_covered": "Bomikhal/Mancheswar",
        "households": 1100,
        "cost_lakh": 62.0,
        "hh_per_lakh": 17.7,
        "type": "infra",
        "description": "Feeder upgrades to cut technical losses and improve reliability.",
    },
    {
        "id": 5,
        "rank": 5,
        "name": "PM-KUSUM Subsidy Facilitation",
        "wards_covered": "All Critical",
        "households": 2400,
        "cost_lakh": 140.0,
        "hh_per_lakh": 17.1,
        "type": "policy",
        "description": "Facilitate subsidy access for distributed solar adoption.",
    },
    {
        "id": 6,
        "rank": 6,
        "name": "LED Streetlight + DG Offset",
        "wards_covered": "Rasulgarh",
        "households": 540,
        "cost_lakh": 32.0,
        "hh_per_lakh": 16.9,
        "type": "quick",
        "description": "Efficiency upgrades and diesel generator offset program.",
    },
    {
        "id": 7,
        "rank": 7,
        "name": "Solar Pump + Agri Grid Relief",
        "wards_covered": "Aiginia Outskirts",
        "households": 380,
        "cost_lakh": 26.0,
        "hh_per_lakh": 14.6,
        "type": "infra",
        "description": "Solar pumping to reduce agri grid stress.",
    },
]

CITY_SEED: List[Dict] = [
    {
        "id": 1,
        "name": "Bhubaneswar",
        "state": "Odisha",
        "epi": 0.74,
        "outage": 5.6,
        "burden": 11.8,
        "reliability": 0.82,
        "grid_loss": 12.4,
        "renewable": 18.2,
        "tariff": 6.1,
    },
    {
        "id": 2,
        "name": "Kolkata",
        "state": "West Bengal",
        "epi": 0.69,
        "outage": 4.1,
        "burden": 10.5,
        "reliability": 0.85,
        "grid_loss": 11.1,
        "renewable": 14.8,
        "tariff": 6.6,
    },
    {
        "id": 3,
        "name": "Patna",
        "state": "Bihar",
        "epi": 0.58,
        "outage": 6.9,
        "burden": 13.6,
        "reliability": 0.76,
        "grid_loss": 15.2,
        "renewable": 12.1,
        "tariff": 5.8,
    },
    {
        "id": 4,
        "name": "Pune",
        "state": "Maharashtra",
        "epi": 0.79,
        "outage": 3.4,
        "burden": 9.2,
        "reliability": 0.88,
        "grid_loss": 9.6,
        "renewable": 22.5,
        "tariff": 7.1,
    },
    {
        "id": 5,
        "name": "Surat",
        "state": "Gujarat",
        "epi": 0.73,
        "outage": 3.8,
        "burden": 9.7,
        "reliability": 0.86,
        "grid_loss": 10.2,
        "renewable": 20.9,
        "tariff": 6.4,
    },
    {
        "id": 6,
        "name": "National Optimal Standard",
        "state": "India",
        "epi": 0.92,
        "outage": 1.2,
        "burden": 6.0,
        "reliability": 0.96,
        "grid_loss": 6.5,
        "renewable": 35.0,
        "tariff": 5.5,
    },
]


def get_mock_wards():
    now = datetime.utcnow()
    return [{**ward, "created_at": now} for ward in WARD_SEED]


def get_mock_ward_by_id(ward_id: int) -> Dict:
    for ward in WARD_SEED:
        if ward["id"] == ward_id:
            return {**ward, "created_at": datetime.utcnow()}
    base = WARD_SEED[0]
    return {
        **base,
        "id": ward_id,
        "name": f"Ward {ward_id}",
        "created_at": datetime.utcnow(),
    }
